package: maintenance
version: '3.4.0'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/maintenance
title: translate:maintenance_title

page:
    title: translate:maintenance_title
    perm: maintenance[]  # Grundlegendes Recht für den Zugriff auf das Addon
    prio: 81
    block: system
    icon: 'maintenance rex-icon fa-toggle-off'
    subpages:
        frontend:
            title: translate:maintenance_frontend_title
            icon: rex-icon fa-user
            perm: maintenance[frontend]
            subpages:
                index:
                    title: translate:maintenance_frontend_general_title
                    icon: rex-icon fa-sliders
                    perm: maintenance[frontend]
                advanced:
                    title: translate:maintenance_settings_title
                    icon: rex-icon fa-cog
                    perm: admin[]
                announcement:
                    title: translate:maintenance_announcement_title
                    icon: rex-icon fa-bullhorn
                    perm: admin[]
        backend:
            title: translate:maintenance_backend_title
            icon: rex-icon fa-user-gear
            perm: admin[]
        domains:
            title: translate:maintenance_domains_title
            icon: rex-icon fa-sitemap
            perm: maintenance[frontend]
        preview:
            title: translate:maintenance_preview_title
            icon: rex-icon fa-eye
            hidden: true
            perm: maintenance[frontend]
        help:
            title: translate:maintenance_docs_title
            subPath: README.md
            icon: rex-icon fa-question-circle
            itemClass: pull-right
            perm: maintenance[]

requires:
    redaxo: ^5.17.0
    php:
        version: '>=8.2'

# Definition der verfügbaren Rechte für die Rollenverwaltung
permissions:
    maintenance[]: translate:maintenance[] # Grundlegendes Recht
    maintenance[frontend]: translate:maintenance[frontend] # Recht für Frontend-Einstellungen

console_commands:
       maintenance:mode: rex_maintenance_mode_command

default_config:
      http_response_code: 503 # 503, 403
      allowed_ips: ''
      allowed_yrewrite_domains: ''
      authentication_mode: 'URL'  # `URL`, `password`
      block_frontend: 0
      block_frontend_rex_user: 0
      block_backend: 0
      redirect_frontend_to_url: '' # `https://example.com/maintenance.html`
      redirect_backend_to_url: '' # `https://example.com/maintenance.html`
      secret: ''
      editor: 'class="form-control cke5-editor" data-profile="default"'
      maintenance_frontend_headline: 'Maintenance / Wartung'
      maintenance_text_en: 'This website is temporarily unavailable.'
      maintenance_text_de: 'Diese Website ist vorübergehend nicht erreichbar.'
      maintenance_backend_headline: 'Maintenance / Wartung'
      maintenance_frontend_update_interval: 60
      maintenance_backend_update_interval: 60
      domain_status: []
      all_domains_locked: false

installer_ignore:
    - .git
    - .github
    - .gitignore
    - node_modules
    - tests
    - tests_output
    - nightwatch.conf.js
    - package.json
    - package-lock.json
    - yarn.lock
