package: maintenance
version: '1.3.0-dev'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/maintenance
title: 'Maintenance'
nav_icon: fa-share
kurzbeschreibung: 'Umleitung der Frontendseite auf eine beliebige URL wenn der Besucher nicht im Backend angemeldet ist oder nicht der hintelegten IP entspricht'
umgebung: Fronend

page:
    title: 'Maintenance'
    perm: maintenance[]
    block: system
    icon: 'rex-icon fa-exclamation-triangle'
    subpages:
        frontend:
            { title: 'Frontend', icon: rex-icon fa-laptop }
        backend:
            { title: 'Backend', icon: rex-icon fa-stack-overflow }
        help:
            { title: 'translate:Help', icon: rex-icon fa-info-circle }
requires:
    redaxo: ^5.4.0
