package: maintenance
version: '3.3.0'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/maintenance
title: translate:maintenance_title

page:
    title: translate:maintenance_title
    perm: maintenance[]  # Grundlegendes Recht f端r den Zugriff auf das Addon
    prio: 81
    block: system
    icon: 'maintenance rex-icon fa-toggle-off'
    subpages:
        frontend:
            title: translate:maintenance_frontend_title
            icon: rex-icon fa-user
            perm: maintenance[frontend]
        backend:
            title: translate:maintenance_backend_title
            icon: rex-icon fa-user-gear
            perm: admin[]
        preview:
            title: translate:maintenance_preview_title
            icon: rex-icon fa-eye
            hidden: true
            perm: maintenance[frontend]
        help:
            title: translate:maintenance_docs_title
            subPath: README.md
            icon: rex-icon fa-question-circle
            itemClass: pull-right
            perm: maintenance[]

requires:
    redaxo: ^5.17.0
    php:
        version: '>=8.2'

# Definition der verf端gbaren Rechte f端r die Rollenverwaltung
permissions:
    maintenance[]: translate:maintenance[] # Grundlegendes Recht
    maintenance[frontend]: translate:maintenance[frontend] # Recht f端r Frontend-Einstellungen

console_commands:
       maintenance:mode: rex_maintenance_mode_command

default_config:
      http_response_code: 503 # 503, 403
      allowed_ips: ''
      authentification_mode: 'URL'  # `URL`, `password`
      block_frontend: 0
      block_frontend_rex_user: 0
      block_backend: 0
      redirect_frontend_to_url: '' # `https://example.com/maintenance.html`
      redirect_backend_to_url: '' # `https://example.com/maintenance.html`
      secret: ''
      editor: 'class="form-control redactor-editor--default"'
      maintenance_frontend_headline: 'Maintenance / Wartung'
      maintenance_backend_headline: 'Maintenance / Wartung'
      maintenance_frontend_update_interval: 60
      maintenance_backend_update_interval: 60

installer_ignore:
    - .git
    - .github
    - .gitignore
    - node_modules
    - tests
    - tests_output
    - nightwatch.conf.js
    - package.json
    - package-lock.json
    - yarn.lock
