package: maintenance
version: '2.8.7'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/maintenance
title: 'Maintenance'
nav_icon: fa-share
kurzbeschreibung: 'Umleitung der Frontendseite auf eine beliebige URL wenn der Besucher nicht im Backend angemeldet ist oder nicht der hintelegten IP entspricht'
umgebung: Frontend

page:
    title: 'Maintenance'
    perm: maintenance[]
    block: system
    icon: 'maintenance rex-icon fa-exclamation-triangle'
    subpages:
        frontend:
            { title: 'Frontend', icon: rex-icon fa-laptop }
        backend:
            { title: 'Backend', icon: rex-icon fa-stack-overflow }
        help:
            { title: 'translate:Help', subPath: README.md }
requires:
    redaxo: ^5.7.0
    php:
        version: '>=7.4' 
        
console_commands:
       maintenance:on: rex_maintenance_command_on
       frontend:on: rex_maintenance_command_on
       maintenance:off: rex_maintenance_command_off
       frontend:off: rex_maintenance_command_off

default_config:
      responsecode: 503
      ip: ''
      frontend_aktiv: 'Deaktivieren'
      redirect_frontend: ''
      redirect_backend: ''
      backend_aktiv: '0'
      blockSession: 'Inaktiv'
      secret: ''
