package: maintenance
version: '3.0.0-dev'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/maintenance
title: translate:maintenance_title

page:
    title: translate:maintenance_title
    perm: maintenance[]
    prio: 81
    block: system
    icon: 'maintenance rex-icon fa-toggle-off'
    subpages:
        frontend:
            title: translate:maintenance_frontend_title
            icon: rex-icon fa-user
        backend:
            title: translate:maintenance_backend_title
            icon: rex-icon fa-user-gear
        help:
            title: translate:maintenance_docs_title
            subPath: README.md
            icon: rex-icon fa-question-circle
            itemClass: pull-right
requires:
    redaxo: ^5.17.0
    php:
        version: '>=8.2'
        
console_commands:
       maintenance:frontend_disable: rex_maintenance_command_on
       maintenance:frontend_enable: rex_maintenance_command_off

default_config:
      http_response_code: 503 # 503, 403
      allowed_ips: false
      authentification_mode: 'url'  # `url`, `password`
      block_frontend_rex_user: false
      block_frontend: true
      block_backend: false
      redirect_frontend_to_url: '' # `https://example.com/maintenance.html`
      redirect_backend_to_url: '' # `https://example.com/maintenance.html`
      secret: ''

installer_ignore:
    - .git
    - .github
    - .gitignore
    - node_modules
    - tests
    - tests_output
    - nightwatch.conf.js
    - package.json
    - package-lock.json
    - yarn.lock
